### ISSUE TITLE
SW Module HAL_GPIO

### ISSUE THREAD

**Issue by pastorpflores** [WattRex/Regenerative-Battery-Cycler#7]
**Module functionalities**
- Set output leds
- Enable DRMOS
- Reads DRMOS temp warn
- Reads Vstatus inputs

**Comment by RobertoAldea** [comment]
#5 @mariuscrsn Review naming convention for GPIO inputs and outputs.

**Comment by pastorpflores** [comment]
@RobertoAldea

- Advanced in local. Not integrated yet. 
- Test functions not done yet. 
- 
Moved to week 22.

**Comment by pastorpflores** [comment]
Module done
