### ISSUE TITLE
SW Module HAL_PWM

### ISSUE THREAD

**Issue by pastorpflores** [WattRex/Regenerative-Battery-Cycler#8]
**Module functionalities**
- Enables/disables PWM
- Set duty

**Comment by pastorpflores** [comment]
Delays in Week 21. Therefore, moved to Week 23.

**Comment by RobertoAldea** [comment]
#5 @mariuscrsn Change interface of the module, its neccessary to use a uint32_t instead of a uint8_t, so the final interface will be as following:
```
HAL_PWM_result_e HAL_PwmInit(void)
HAL_PWM_result_e HAL_PwmSetDuty(const uint32_t duty)
HAL_PWM_result_e HAL_PwmStart (void)
HAL_PWM_result_e HAL_PwmStop (void)
```
